name: Expo Build and Publish

on:
  push:
    branches:
      - main

jobs:
  expo_build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install project dependencies
        run: yarn install

      - name: Authenticate with Expo
        run: npx expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}

      - name: Build Expo app for Android
        run: npx expo build:android --non-interactive

      - name: Publish to Expo
        run: npx expo publish --platform android --release-channel main # Replace "main" with your desired release channel
